/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#f3e1b6",
        "on-error": "#ffffff",
        "secondary-fixed": "#c7e7ff",
        "inverse-on-surface": "#f4f0ef",
        "pastel-blue": "#EAF9FF",
        surface: "#fcf8f7",
        "primary-fixed-dim": "#c6c4e1",
        "primary-container": "#1d1d33",
        background: "#fcf8f7",
        "on-primary-container": "#85849f",
        "on-background": "#1c1b1b",
        tertiary: "#6a5d3b",
        "primary-fixed": "#e2dffe",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ddd9d8",
        "on-primary-fixed-variant": "#45445d",
        "on-primary-fixed": "#19192f",
        "tertiary-container": "#baaa82",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#d6c59b",
        "surface-tint": "#5d5c75",
        "accent-magenta": "#E94E77",
        "error-container": "#ffdad6",
        "surface-subtle": "#F4F4F4",
        outline: "#78767d",
        "on-secondary-fixed-variant": "#004c6c",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf8f7",
        "surface-container": "#f1edec",
        "on-surface-variant": "#47464d",
        primary: "#050519",
        "on-secondary-container": "#00587d",
        "outline-variant": "#c8c5cd",
        "on-tertiary-fixed": "#231b02",
        "pastel-pink": "#FAF0F4",
        "pastel-yellow": "#FFF9E6",
        "inverse-primary": "#c6c4e1",
        "surface-container-low": "#f7f3f2",
        "on-secondary-fixed": "#001e2e",
        "on-error-container": "#93000a",
        "surface-container-high": "#ebe7e6",
        "surface-container-highest": "#e5e2e1",
        "on-primary": "#ffffff",
        "secondary-container": "#85cfff",
        "secondary-fixed-dim": "#85cfff",
        "on-tertiary-container": "#4a3e1f",
        secondary: "#00658e",
        "on-tertiary-fixed-variant": "#514626",
        "surface-variant": "#e5e2e1",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-surface": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "12px",
        "container-max": "1200px",
        gutter: "32px",
        "section-v-mobile": "80px",
        "stack-md": "24px",
        "section-v": "140px",
      },
      fontFamily: {
        meta: ["Karla"],
        "body-md": ["Karla"],
        "label-caps": ["Karla"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Karla"],
        "display-lg": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
      },
      fontSize: {
        meta: ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "80px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
